---
name: ci
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Tag
        run: |
          TAG=v1
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Docker Build
        run: |
          docker build . -t ghcr.io/${{github.repository}}/test:${TAG}
      - name: "Login to GitHub Container Registry"
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Push
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push ghcr.io/${{github.repository}}/test:${TAG}
