---
name: ci
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Tag
        run: |
          TAG=v9
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Docker Build
        run: |
          docker build . -t ghcr.io/${{github.repository}}/test:${TAG}
      - name: "Login to GitHub Container Registry"
        id: docker_login
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Push
        id: docker_push
        if: steps.docker_login.outcome == 'success'
        run: |
          docker push ghcr.io/${{github.repository}}/test:${TAG}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
#          echo "sha=$TAG" >> $GITHUB_OUTPUT
#      - name: Trigger update of dependent repositories
#        if: steps.docker_push.outcome == 'success'
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          event-type: tag-event
#          client-payload: '{"sha": "${{ github.sha }}", "tag": "${{ env.TAG }}"}'
  update_dependent_repositories:
    name: update_dependent_repositories
    needs: build
    if: ${{ github.event_name == 'push' }}
    uses: glazychev-art/test-docker/.github/workflows/update-dependent-repositories.yaml@main
    with:
      docker_tag: ${{ needs.build.outputs.tag }}
      token: ${{ secrets.BOT_GITHUB_TOKEN }}

